[build-system]
requires = [ "setuptools", "setuptools_scm" ]
build-backend = "setuptools.build_meta"

[project]
name = "ts_mtmount"
description = "CSC that controls the Simonyi Survey Telescope TMA (main axes and related components)."
license = { text = "GPL" }
classifiers = [ "Programming Language :: Python :: 3" ]
urls = { documentation = "https://ts-mtmount.lsst.io", repository = "https://github.com/lsst-ts/ts_mtmount" }
dynamic = [ "version" ]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "python" ]

[project.scripts]
command_mtmount = "lsst.ts.mtmount:command_mtmount"
monitor_mtmount_telemetry = "lsst.ts.mtmount.monitor_mtmount_telemetry:monitor_mtmount_telemetry"
run_mock_tma = "lsst.ts.mtmount.mock:run_mock_tma"
run_mtmount = "lsst.ts.mtmount:run_mtmount"
run_mtmount_telemetry_client = "lsst.ts.mtmount:run_mtmount_telemetry_client"
run_tma_telemetry_config_parser = "lsst.ts.mtmount:run_tma_telemetry_config_parser"

[tool.setuptools_scm]
write_to = "python/lsst/ts/mtmount/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

[tool.pytest.ini_options]
asyncio_mode = "auto"

[project.optional-dependencies]
dev = ["documenteer[pipelines]"]
