{% set data= load_setup_py_data() %}
package:
  name: ts-mtmount
  version: {{ data.get('version') }}

source:
  path: ../

build:
  string: ugly_ccw_only_hack_fall22
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - command_mtmount = lsst.ts.mtmount:command_mtmount
    - command_tma = lsst.ts.mtmount:command_tma
    - monitor_mtmount_telemetry = lsst.ts.mtmount.monitor_mtmount_telemetry:monitor_mtmount_telemetry
    - run_mock_tma = lsst.ts.mtmount.mock:run_mock_tma
    - run_mtmount = lsst.ts.mtmount:run_mtmount
    - run_mtmount_telemetry_client = lsst.ts.mtmount:run_mtmount_telemetry_client

test:
  requires:
    - ts-conda-build =0.3
    - ts-tcpip
    - ts-simactuators
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
  commands:
    - pytest -vsx

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-simactuators
    - ts-tcpip
    - ts-idl
