{% set data= load_setup_py_data() %}
package:
  name: ts-mtmount
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - ts-xml {{ xml_conda_version }}
    - ts-salobj {{ salobj_version }}
    - ts-simactuators
    - ts-tcpip
  source_files:
    - bin
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-xml {{ xml_conda_version }}
    - ts-salobj {{ salobj_version }}
    - ts-simactuators
    - ts-tcpip
